blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('send_mail.urls', namespace='send_mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': True,
            'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    description = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    create_date = models.DateField(auto_now_add=True, verbose_name='дата создания')
    count_views = models.IntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ['count_views']

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:blog')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'description', 'image')

    def get_success_url(self):
        return reverse('blog:view_blog', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить блог "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'blog:blog' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'send_mail/base.html'%}
{% block content %}
<div class="row text-center">
    <div class="col-md-8">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            {{ object.title }}
        </h3>

        <article class="blog-post">
            <p>{{ object.description }}</p>
        </article>

    </div>

</div>
{% if object.image %}
<div class="col-auto d-none d-lg-block">
    <img src="/media/{{ object.image }}"/>
    {% endif %}
</div>
<div class="card-footer">
    Просмотры: {{ object.count_views }}
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'send_mail/base.html' %}
{% block content %}

<main class="container">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 mx-auto text-center">
            <h1 class="display-4">Блог Skystore</h1>
        </div>
    </div>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create_blog' %}">Добавить новый блог</a>
    </div>
    {% for object in object_list %}
    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                {% if object.image %}
                <div class="col-md-12">
                    <img src="/media/{{ object.image }}" class="w-100" alt="{{ object.title }}">
                </div>
                {% endif %}
                <div class="col p-4 d-flex flex-column position-static">
                    <h3 class="mb-0">{{ object.title }}</h3>
                    <div class="mb-1 text-muted">{{ object.create_date }}</div>
                    <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                       href="{% url 'blog:view_blog' object.pk %}">Посмотреть</a>
                    <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                       href="{% url 'blog:edit_blog' object.pk %}">Изменить</a>
                    <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                       href="{% url 'blog:delete_blog' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</main>

</body>
</html>
{% endblock %}