blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('send_mail.urls', namespace='send_mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', verification_user, name='verification'),
    path('success_verification/', success_verification, name='success_verification'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list/', UserListView.as_view(), name='list'),
    path('list/block/<int:pk>', block_user, name='block_user'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True,
            'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    key = models.IntegerField(verbose_name='ключ', **NULLABLE)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "available":
                field.widget.attrs['class'] = 'form-control'


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class VerificationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('key',)

users/views.py
import random

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.views.generic import CreateView, ListView

from users.forms import *
from users.models import User
from users.services import *


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save()
        user.save()

        key = random.randint(1000, 9999)
        user_email = self.request.POST.get('email')

        self.request.session['user_email'] = user_email
        self.request.session['key'] = key
        user_email = self.request.POST.get('email')
        send_verification_mail(user_email, key)

        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:verification')


def verification_user(request):
    key = request.session.get('key')
    user_email = request.session.get('user_email')

    user = get_object_or_404(User, email=user_email)

    if request.method == 'POST':
        form = VerificationForm(request.POST)
        if form.is_valid():
            entered_key = form.cleaned_data['key']
            if entered_key == key:
                if not user.is_verified:
                    user.is_verified = True
                    user.save()
                return redirect('users:success_verification')
    else:
        form = VerificationForm()
    return render(request, 'users/verification.html', {'form': form})


def success_verification(request):
    return render(request, 'users/success_verification.html')


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    model = User

    def get_success_url(self):
        return reverse_lazy('send_mail:mails')


class LogoutView(BaseLogoutView):

    def get_success_url(self):
        return reverse_lazy('send_mail:mails')


class UserListView(ListView):
    model = User


@login_required
def block_user(request, pk):
    if request.user.groups.filter(name="manager").exists() or request.user.is_superuser:
        user = User.objects.get(pk=pk)
        if not user.is_active:
            user.is_active = True
            user.save()
        else:
            user.is_active = False
            user.save()
        return redirect(reverse('users:list'))
    else:
        raise PermissionDenied('Доступ запрещен')

users/templates/users/login.html
{% extends 'send_mail/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Вход
        </div>
        <form method="post" class="row">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'send_mail/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Регистрация
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Подтвердить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/success_verification.html
{% extends 'send_mail/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Верификация успешна пройдена!</h1>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Сервис рассылок - это отличный вариант отправки уведомлений большому количеству пользователей.</p>
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Пользователь {{ object.pk }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    Почта: {{ object.email }}
                </ul>
                {% if object.is_active %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'users:block_user' object.pk %}">Заблокировать пользователя</a>
                {% else %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'users:block_user' object.pk %}">Разблокировать пользователя</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

users/templates/users/verification.html
{% extends 'send_mail/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Верификация
        </div>
        <form method="post" class="row">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Подтвердить
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}