blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('send_mail.urls', namespace='send_mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

send_mail/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from send_mail.apps import SendMailConfig

from send_mail.views import *

app_name = SendMailConfig.name

urlpatterns = [
    path('', cache_page(30)(index), name='index'),
    path('settings/', MailListView.as_view(), name='settings'),
    path('settings/create/', MailCreateView.as_view(), name='create_settings'),
    path('settings/view/<int:pk>/', MailDetailView.as_view(), name='view_settings'),
    path('settings/edit/<int:pk>/', MailUpdateView.as_view(), name='edit_settings'),
    path('settings/delete/<int:pk>/', MailDeleteView.as_view(), name='delete_settings'),

    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/', ClientListView.as_view(), name='clients'),

    path('messages/', TextMailListView.as_view(), name='messages'),
    path('message/create/', TextMailCreateView.as_view(), name='create_message'),
    path('message/view/<int:pk>/', TextMailDetailView.as_view(), name='view_message'),
    path('message/edit/<int:pk>/', TextMailUpdateView.as_view(), name='edit_message'),
    path('message/delete/<int:pk>/', TextMailDeleteView.as_view(), name='delete_message'),

    path('mails/', MailingClientListView.as_view(), name='mails'),
    path('mails/create', MailingClientCreateView.as_view(), name='create_mail'),
    path('mails/view/<int:pk>', MailingClientDetailView.as_view(), name='view_mail'),
    path('mails/edit/<int:pk>', MailingClientUpdateView.as_view(), name='edit_mail'),
    path('mails/delete/<int:pk>', MailingClientDeleteView.as_view(), name='delete_mail'),

    path('mails/status/<int:pk>/', stop_mailing, name='stop_mailing'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', verification_user, name='verification'),
    path('success_verification/', success_verification, name='success_verification'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list/', UserListView.as_view(), name='list'),
    path('list/block/<int:pk>', block_user, name='block_user'),
]

send_mail/models.py
import django
from django.db import models

NULLABLE = {'blank': True,
            'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='почта')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    mail = models.ForeignKey('MailingClient', on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('full_name',)


class MailSettings(models.Model):
    PERIOD_CHOICES = (
        ('D', 'Каждый день'),
        ('W', 'Каждую неделю'),
        ('M', 'Каждый месяц')
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('active', 'Запущена'),
        ('closed', 'Завершена')
    )

    start_time = models.TimeField(verbose_name='время старта рассылки', default='09:00')
    end_time = models.TimeField(verbose_name='время окончания рассылки', default='00:00')
    period = models.CharField(max_length=30, verbose_name='периодичность', choices=PERIOD_CHOICES)
    status = models.CharField(max_length=10, verbose_name='статус рассылки', choices=STATUS_CHOICES, default='created')

    message = models.ForeignKey('TextMail', on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)

    def __str__(self):
        return f'{self.pk}'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'


class TextMail(models.Model):
    topic = models.CharField(max_length=200, verbose_name='тема')
    body = models.TextField(verbose_name='сообщение')

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщения для рассылки'


class LogMail(models.Model):
    time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.BooleanField(default=True, verbose_name='статус последней попытки')
    response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)

    settings = models.ForeignKey(MailSettings, on_delete=models.CASCADE, verbose_name='настройка')

    class Meta:
        verbose_name = 'Логи сообщения'
        verbose_name_plural = 'Логи сообщения'


class MailingClient(models.Model):
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    settings = models.ForeignKey(MailSettings, on_delete=models.CASCADE, verbose_name='настройка', **NULLABLE)

    created_by = models.ForeignKey(django.conf.settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   verbose_name='создано пользователем', **NULLABLE)

    def __str__(self):
        return f'{self.clients} {self.settings}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

send_mail/forms.py
from django import forms

from send_mail.models import MailSettings, TextMail, Client, MailingClient


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailSettings
        fields = '__all__'


class TextMailForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = TextMail
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MailingClientForm(forms.ModelForm):

    class Meta:
        model = MailingClient
        fields = ['settings']

send_mail/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from send_mail.forms import MailSettingsForm, ClientForm, TextMailForm, MailingClientForm
from send_mail.models import MailSettings, TextMail, Client, MailingClient


class ManagerRequiredMixin:

    def dispatch(self, request, *args, **kwargs):
        if request.user.groups.filter(name="manager").exists():
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


def index(request):
    blog = Blog.objects.all()
    mailing_is_active = MailSettings.objects.filter(status='active')
    client_mailing = MailingClient.objects.all()
    unique_clients = client_mailing.values_list('clients', flat=True).distinct()
    random_articles = sample(list(blog), k=min(len(blog), 3))

    context = {
        'random_articles': random_articles,
        'total_mailings': len(client_mailing),
        'active_mailings': len(mailing_is_active),
        'unique_clients': len(unique_clients)
    }

    return render(request, 'send_mail/home.html', context)


class MailListView(LoginRequiredMixin, ListView):
    model = MailSettings


class MailCreateView(LoginRequiredMixin, CreateView):
    model = MailSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy('send_mail:settings')

    def form_valid(self, form):
        return super().form_valid(form)


class MailDetailView(LoginRequiredMixin, DetailView):
    model = MailSettings


class MailUpdateView(LoginRequiredMixin, UpdateView):
    model = MailSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy('send_mail:settings')

    def form_valid(self, form):
        return super().form_valid(form)


class MailDeleteView(LoginRequiredMixin, DeleteView):
    model = MailSettings
    success_url = reverse_lazy('send_mail:settings')


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('send_mail:clients')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client

    def get_success_url(self):
        return reverse_lazy('send_mail:clients')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('send_mail:clients')


class TextMailCreateView(ManagerRequiredMixin, LoginRequiredMixin, CreateView):
    model = TextMail
    form_class = TextMailForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('send_mail:messages')


class TextMailListView(LoginRequiredMixin, ListView):
    model = TextMail


class TextMailUpdateView(ManagerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = TextMail
    form_class = TextMailForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('send_mail:messages')


class TextMailDeleteView(ManagerRequiredMixin, LoginRequiredMixin, DeleteView):
    model = TextMail

    def get_success_url(self):
        return reverse_lazy('send_mail:messages')


class TextMailDetailView(ManagerRequiredMixin, LoginRequiredMixin, DetailView):
    model = TextMail


class MailingClientListView(ListView):
    model = MailingClient

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return MailingClient.objects.none()

        if self.request.user.groups.filter(name="manager").exists() or self.request.user.is_superuser:
            return MailingClient.objects.all()

        return MailingClient.objects.filter(created_by=self.request.user)


class MailingClientCreateView(ManagerRequiredMixin, CreateView):
    model = MailingClient
    form_class = MailingClientForm

    def form_valid(self, form):
        mailing_client = form.save(commit=False)
        selected_client_ids = self.request.POST.getlist('selected_clients')

        if selected_client_ids:
            mailing_client.created_by = self.request.user
            mailing_client.save()
            mailing_client.clients.set(selected_client_ids)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = Client.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy('send_mail:mails')


class MailingClientDetailView(ManagerRequiredMixin, DetailView):
    model = MailingClient


class MailingClientUpdateView(ManagerRequiredMixin, UpdateView):
    model = MailingClient
    form_class = MailingClientForm

    def form_valid(self, form):
        mailing_client = form.save(commit=False)
        selected_client_ids = self.request.POST.getlist('selected_clients')

        if selected_client_ids:
            mailing_client.created_by = self.request.user
            mailing_client.save()
            mailing_client.clients.set(selected_client_ids)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = Client.objects.all()
        mailing_client = self.get_object()
        context['selected_clients'] = mailing_client.clients.all()
        return context

    def get_success_url(self):
        return reverse_lazy('send_mail:mails')


class MailingClientDeleteView(ManagerRequiredMixin, DeleteView):
    model = MailingClient

    def get_success_url(self):
        return reverse_lazy('send_mail:mails')


def stop_mailing(request, pk):
    if not request.user.groups.filter(name="manager").exists() and not request.user.is_superuser:
        raise PermissionDenied
    mailing = MailingClient.objects.get(pk=pk)
    if mailing.settings.status == 'active' or mailing.settings.status == 'created':
        mailing.settings.status = 'closed'
        mailing.save()
    else:
        mailing.settings.status = 'active'
        mailing.save()
    return redirect(reverse('send_mail:mails'))

send_mail/templates/send_mail/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылок</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис рассылок</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'send_mail:index' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'send_mail:mails' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'send_mail:settings' %}">Настройки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'send_mail:clients' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'send_mail:messages' %}">Сообщения</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog' %}">Блог</a>
    </nav>
    <nav class="ms-md-auto">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:list' %}">Список пользователей</a>
            {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>


<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Сервис рассылок
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

send_mail/templates/send_mail/client_confirm_delete.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить клиента "{{ object.full_name }}"?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'send_mail:clients' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/client_form.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mail_confirm_delete.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить рассылку "{{ object.message.topic }}"?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'send_mail:index' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mail_detail.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Тема рассылки: {{ object.message.topic }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Описание рассылки: {{ object.message.body }}
                    </p>
                    <p>
                        Статус рассылки: {{ object.status }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mail_form.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mail_list.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Сервис рассылок - это отличный вариант отправки уведомлений большому количеству пользователей.</p>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'send_mail:create_mail' %}">Добавить новую рассылку</a>
    </div>
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.message.topic }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {{ object.message.body|truncatechars:45 }}
                </ul>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'send_mail:view_mail' object.pk %}">Посмотреть</a>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'send_mail:edit_mail' object.pk %}">Изменить</a>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'send_mail:delete_mail' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

send_mail/templates/send_mail/mailingclient_confirm_delete.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить рассылку {{ object.id }}?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'send_mail:mails' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mailingclient_form.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <hr>
                        <div id="selected-clients-container">
                            <h4 class="font-weight-normal">Выбранные клиенты</h4>
                            <ul id="selected-clients-list" class="list-unstyled">
                                {% for client in selected_clients %}
                                <li data-client-id="{{ client.id }}">
                                    {{ client.full_name }} ({{ client.email }})
                                    <input type="hidden" name="selected_clients" value="{{ client.id }}">
                                    <button type="button" class="btn btn-danger remove-client">Удалить</button>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <select id="client-selection" class="form-control">
                        <option value="">Выберите клиента</option>
                        {% for client in clients %}
                        <option value="{{ client.id }}" data-client-name="{{ client.full_name }}" data-client-email="{{ client.email }}">{{ client.full_name }} ({{ client.email }})</option>
                        {% endfor %}
                    </select>
                    <button type="button" class="btn btn-success add-client mt-3">Добавить клиента</button>
                </div>
            </div>
            <div id="warning-message" style="display: none;" class="alert alert-warning mt-3">
                Клиент уже добавлен
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    const selectedClientsList = $('#selected-clients-list');
    const warningMessage = $('#warning-message');
    const clientSelection = $('#client-selection');

    $('.add-client').click(function() {
        const selectedOption = clientSelection.find('option:selected');
        const selectedClientId = selectedOption.val();

        if (selectedClientId) {
            const selectedClientNameValue = selectedOption.data('client-name');
            const selectedClientEmailValue = selectedOption.data('client-email');

            if (!selectedClientsList.find(`li[data-client-id="${selectedClientId}"]`).length) {
                const listItem = `<li data-client-id="${selectedClientId}">${selectedClientNameValue} (${selectedClientEmailValue}) <input type="hidden" name="selected_clients" value="${selectedClientId}"> <button type="button" class="btn btn-danger remove-client">Удалить</button></li>`;
                selectedClientsList.append(listItem);
            } else {
                warningMessage.show();
                setTimeout(function() {
                    warningMessage.hide();
                }, 3000);
            }
        }
    });

    selectedClientsList.on('click', '.remove-client', function() {
        $(this).closest('li').remove();
    });
});
</script>

<style>
    #selected-clients-list li {
        margin-bottom: 8px;
    }
</style>
{% endblock %}

send_mail/templates/send_mail/mailingclient_list.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Сервис рассылок - это отличный вариант отправки уведомлений большому количеству пользователей.</p>
    <div class="col-12 mb-5">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'send_mail:create_mail' %}">Добавить новую рассылку</a>
        {% else %}
        <div class="alert alert-warning" style="display: inline-block;" role="alert">
            Для создания рассылки, пожалуйста, войдите в систему.
        </div>
        {% endif %}
    </div>


    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    Номер рассылки: {{ object.pk }}
                </h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    Количество клиентов: {{ object.clients.all.count }}
                </ul>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    Номер настройки: {{ object.settings.id }}
                </ul>
                {% if not user.is_staff or user.is_superuser %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:view_mail' object.pk %}">Посмотреть</a>
                {% endif %}
                {% if not user.is_staff or user.is_superuser %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:edit_mail' object.pk %}">Изменить</a>
                {% endif %}
                {% if not user.is_staff or user.is_superuser %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:delete_mail' object.pk %}">Удалить</a>
                {% endif %}
                {% if user.is_staff %}
                {% if object.settings.status == 'active' %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:stop_mailing' object.pk %}">Остановить рассылку</a>
                {% else %}
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:stop_mailing' object.pk %}">Запустить рассылку</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

send_mail/templates/send_mail/mailsettings_confirm_delete.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить настройку {{ object.pk }}?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'send_mail:settings' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mailsettings_form.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

send_mail/templates/send_mail/mailsettings_list.html
{% extends 'send_mail/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    <p class="lead">Сервис рассылок - это отличный вариант отправки уведомлений большому количеству пользователей.</p>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'send_mail:create_settings' %}">Добавить новую настройку</a>
    </div>
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Настройка {{ object.pk }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    Статус: {{ object.get_status_display }}
                </ul>
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:view_settings' object.pk %}">Посмотреть</a>
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:edit_settings' object.pk %}">Изменить</a>
                <a class="btn btn-lg btn-block btn-outline-primary mt-3"
                   href="{% url 'send_mail:delete_settings' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}